import React from 'react';
import './about.css';
import pic1 from '../../picture/gallery-bunny/1254.png'
import pic2 from '../../picture/gallery-bunny/2.png'
import pic3 from '../../picture/gallery-bunny/3.png'
import pic4 from '../../picture/gallery-bunny/4.png'
import pic5 from '../../picture/gallery-bunny/5.png'
import pic6 from '../../picture/gallery-bunny/6.png'
import pic7 from '../../picture/gallery-bunny/7.png'
import pic8 from '../../picture/gallery-bunny/8.png'
import pic9 from '../../picture/gallery-bunny/9.png'
import pic10 from '../../picture/gallery-bunny/10.png'

const About = () => {
    return (
        <main className="main" id="about">
            <div className="about">
                <h1 className="about__title">ICPBunny</h1>
                <p className="about__text">Our NFT's are generated by the user and not by us. Meaning NFT's that you will be minting is purely done by you and we make sure it is saved in our canister.Our NFT's are generated by the user and not by us. Meaning NFT's that you will be minting is purely done by you and we make sure it is saved in our canister.Our NFT's are generated by the user and not by us. Meaning NFT's that you will be minting is purely done by you and we make sure it is saved in our canister.Our NFT's are generated by the user and not by us. Meaning NFT's that you will be minting is purely done by you and we make sure it is saved in our canister</p>
            </div>

            <div className="animation-section">
                <div className="animation">
                    <div className="animation-items">
                        <img src="https://i.ibb.co/BNWrjFj/475.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/Qf2xF6s/1380.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/ydFyTnS/1261.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/KWghgNG/1263.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/YDznTxz/1258.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/QDS6sF0/1381.png" alt="" className="bunny-baner"/>
                    </div>
                    <div className="animation-items">
                        <img src="https://i.ibb.co/BNWrjFj/475.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/Qf2xF6s/1380.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/ydFyTnS/1261.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/KWghgNG/1263.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/YDznTxz/1258.png" alt="" className="bunny-baner"/>
                        <img src="https://i.ibb.co/QDS6sF0/1381.png" alt="" className="bunny-baner"/>
                    </div>
                </div>
            </div>

            <h2 className="about__title-sub">BunnyProtocol</h2>
            <p className="about__text">Simple Storage Protocol #BunnyProtocol
                On chain NFT minting is a huge challenge and we solved that with our own proprietary Protocol #BunnyProtocol powered by #Dfinity (The Internet of Computers)
                Simple Storage Protocol (SSP)— NFT Distribution across micro-canisters.
                We call it as #BunnyProtocol
                We welcome critics from #devs & community.
            </p>
            <div className="protocol-container">
                <a href="https://miro.medium.com/max/1324/0*0Weh2Bkeghecv_GP"><img src="https://miro.medium.com/max/1324/0*0Weh2Bkeghecv_GP" alt="" className="protocol-image"/></a>
            </div>

            <div className="gallery">
                <h2 className="gallery__title-sub">ICPBunny Gallery</h2>
                <div className="gallery__pict">
                    <img src={pic1} className="gallery-item" alt=""/>
                    <img src={pic2} className="gallery-item" alt=""/>
                    <img src={pic3} className="gallery-item" alt=""/>
                    <img src={pic4} className="gallery-item" alt=""/>
                    <img src={pic5} className="gallery-item gallery-item5" alt=""/>
                    <img src={pic6} className="gallery-item gallery-item6" alt=""/>
                    <img src={pic7} className="gallery-item gallery-item7" alt=""/>
                    <img src={pic8} className="gallery-item" alt=""/>
                    <img src={pic9} className="gallery-item gallery-item9" alt=""/>
                    <img src={pic10} className="gallery-item gallery-item10" alt=""/>
                </div>
            </div>
        </main>
    )
}

export default About;